<?php

return [
    'starter' => [
        'nome' => 'Starter',
        'valor' => 49.90,
        'taxa_agendamento_bot' => 0,
        'profissionais' => 3,
        'limite_bot_mes' => 100,  // bot pausa ao atingir
        'retencao_mensagens_dias' => 30,
        'relatorios_avancados' => false,
        'descricao' => 'Perfeito para começar',
        'destaque' => false,
        'features' => [
            'Até 3 profissionais',
            'Bot WhatsApp com IA',
            'Até 100 agendamentos via bot/mês',
            'Agenda visual',
            'Reserva manual pelo painel (grátis)',
            'Histórico de 30 dias',
            'R$ 0,40 por agendamento via bot',
        ],
        'nao_inclui' => [
            'Relatórios avançados',
            'Suporte prioritário',
        ],
    ],
    'pro' => [
        'nome' => 'Pro',
        'valor' => 99.90,
        'taxa_agendamento_bot' => 0,
        'profissionais' => 10,
        'limite_bot_mes' => 350,
        'retencao_mensagens_dias' => 90,
        'relatorios_avancados' => true,
        'descricao' => 'Para negócios em crescimento',
        'destaque' => true,
        'features' => [
            'Até 10 profissionais',
            'Bot WhatsApp com IA',
            'Até 350 agendamentos via bot/mês',
            'Agenda visual',
            'Reserva manual pelo painel (grátis)',
            'Histórico de 90 dias',
            'Relatórios avançados',
            'Suporte prioritário',
            'R$ 0,30 por agendamento via bot',
        ],
        'nao_inclui' => [],
    ],
    'business' => [
        'nome' => 'Business',
        'valor' => 179.90,
        'taxa_agendamento_bot' => 0,
        'profissionais' => null,
        'limite_bot_mes' => null,  // ilimitado
        'retencao_mensagens_dias' => null,
        'relatorios_avancados' => true,
        'descricao' => 'Para operações de alto volume',
        'destaque' => false,
        'features' => [
            'Profissionais ilimitados',
            'Bot WhatsApp com IA',
            'Agendamentos via bot ilimitados',
            'Agenda visual',
            'Reserva manual pelo painel (grátis)',
            'Histórico completo',
            'Relatórios avançados',
            'Suporte prioritário via chat',
            'R$ 0,20 por agendamento via bot',
        ],
        'nao_inclui' => [],
    ],
];
