<?php

return [
    'basico' => [
        'nome'           => 'Básico',
        'valor'          => 79.90,
        'recursos'       => 3,
        'conversas_mes'  => 300,
        'descricao'      => 'Até 3 recursos, 300 conversas/mês',
        'destaque'       => false,
        'features'       => [
            'Bot WhatsApp com IA',
            'Até 3 recursos',
            '300 conversas por mês',
            'Agenda visual',
            'Reserva manual',
            'Histórico de 30 dias',
        ],
        'nao_inclui' => [
            'Relatórios avançados',
            'Suporte prioritário',
            'Histórico de 90 dias',
            'Conversas extras (R$0,50/bloco de 50)',
        ],
    ],
    'profissional' => [
        'nome'           => 'Profissional',
        'valor'          => 129.90,
        'recursos'       => 10,
        'conversas_mes'  => 1500,
        'descricao'      => 'Até 10 recursos, 1.500 conversas/mês',
        'destaque'       => true,
        'features'       => [
            'Bot WhatsApp com IA',
            'Até 10 recursos',
            '1.500 conversas por mês',
            'Agenda visual',
            'Reserva manual',
            'Histórico de 90 dias',
            'Relatórios avançados',
            'Suporte prioritário',
            'Conversas extras (R$0,30/bloco de 50)',
        ],
        'nao_inclui' => [
            'Conversas ilimitadas',
        ],
    ],
    'ilimitado' => [
        'nome'           => 'Ilimitado',
        'valor'          => 199.90,
        'recursos'       => null,
        'conversas_mes'  => null,
        'descricao'      => 'Recursos ilimitados, conversas ilimitadas',
        'destaque'       => false,
        'features'       => [
            'Bot WhatsApp com IA',
            'Recursos ilimitados',
            'Conversas ilimitadas',
            'Agenda visual',
            'Reserva manual',
            'Histórico completo',
            'Relatórios avançados',
            'Suporte prioritário via chat',
        ],
        'nao_inclui' => [],
    ],
];
